import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "bootstrap/dist/css/bootstrap.min.css";
import { Html } from "next/document";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function privateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html>
      <body 
        className="bg-dark text-white font-sans-serif ">
          <h1>layout dentro de private</h1>
        {children}
      </body>
   </html>
  );
}
